# Generated by Django 3.2.7 on 2022-01-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_delete_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
