# Generated by Django 3.2.7 on 2022-01-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
