# Generated by Django 3.2.7 on 2022-01-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_balance_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
